import Providers from "@/components/Providers";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DLayout from "./components/DLayout";
import {getServerSession} from 'next-auth'
import { authOptions } from "../api/auth/[...nextauth]/route";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard Page",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
        <Providers>
          <DLayout session={session}>{children}</DLayout>
        </Providers>
      </body>
    </html>
  );
}
