import Providers from "@/components/Providers";
import "../globals.css";
import type { Metadata } from "next";
import { AppHeader } from "./ui/AppHeader";


export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body >
        <Providers>
        <AppHeader />
        {children}
        </Providers>
      </body>
    </html>
  );
}
